{% set version = '9.0.3' %}

package:
  name: libglu
  version: {{ version }}

source:
  url: https://gitlab.freedesktop.org/mesa/glu/-/archive/glu-{{ version }}/glu-glu-{{ version }}.tar.bz2
  sha256: 38044ee4f255578165a54eaeb089b67fb64f7f7c0ce5fa690cd47c9df10b263c
  patches:
    # https://gitlab.freedesktop.org/mesa/glu/-/merge_requests/13
    - 0001-Fix-opengl-gl-typo.-pkg-config-expects-gl-not-opengl.patch

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - pkg-config                         # [unix]
    - ninja
    - meson
  host:
    - libgl-devel                        # [linux]
    - libegl-devel                       # [linux]
    - libdrm                             # [linux]
    - xorg-libx11                        # [linux]
    - xorg-xorgproto                     # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-libxxf86vm                    # [linux]
    - libxcb                             # [linux]
    # These dependencies are only for cos7 platforms
    - xorg-libxau  # [linux and (ppc64le or aarch64)]
    - xorg-libxdmcp  # [linux and (ppc64le or aarch64)]

test:
  commands:
    - test -f ${PREFIX}/lib/libGLU.a            # [not win]
    - test -f ${PREFIX}/lib/libGLU${SHLIB_EXT}  # [not win]

  # Check dowstreams if needed.
  # downstreams:
  #   - jasper
  #   - freeglut
  #   - vtk-base

about:
  home: https://www.mesa3d.org
  dev_url: https://gitlab.freedesktop.org/mesa/glu
  doc_url: https://gitlab.freedesktop.org/mesa/glu
  license: SSGI-B-1.1 AND SGI-B-2.0 AND MIT
  license_family: Other
  summary: Mesa OpenGL utility library (GLU).
  description: Mesa OpenGL utility library (GLU).

extra:
  recipe-maintainers:
    - bgruening
    - hmaarrfk
