travis:
  secure:
    BINSTAR_TOKEN: EFRLcNaoQxniK70UCsi5YfpgTqEFbmFwA5UaPpxz/InQJveZf4w/zKGLv+grb9laBBp9WbDpZKnIAjhPKlWRMAU0+tDdKixmC0MuNyuWtIx2jvH0IEHQrvitcMH639iiaQ7CbG2L+X6LvFyOpxW1nRvGg9hwYV3952WEJiUSj2zhyRG6xtvrTWpldXlTOaRy7Qw6DET7S7gz5OE0p2i3nzoJ6CxgXgGt7/mpfqRN08+Gq3K+GBvFjftF8ez5C9BLs1yjGznp3sbjj4HmXrcfVbtBiwvc4fqIyz2mwcHgwchXjrg0EZkV+rYJz2KzEqoQRw+N3Ua8E4zTLWwSU9mfRazRE1yG92qnzR6V1uVoVbw99q0jfikGiBxv9idcVBpKb9rF9z6fGIIj6VOSp38oAKfqQGdsyk4QU8lNNI5lzA+xWw16K+FDBMjPdwuSviIRWFwJ4V5sKD+bLyd1CDkM1j86L4A+eKTU9I7hFb/y4lyveLKcsHQ70MD8gunj1q3ySWYXGnB0aDi7xk4EyQxUzd1a/SFeFY0xVJmQq0LV+rITOjzocIEU5dGjj054LNYlsJWQ4FQhgdF59shW4UbZUM3h8k3RqAATMUvYyMrnDGd5jeql0BM57QkASTSNJqeSjFsbYGTa9dfBUuSJ0r2qqhdam+eU6ARufhDqqAJ+0dk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
