travis:
  secure:
    BINSTAR_TOKEN: HiO8bPx4bvl4UNEVkwvZbwtxZn2G5FiEeo1FKiAFPXp4VxuCLCPWf6B7ZHJGYs3plA8HxfqQb0U6c1rGJeNjQMF2sTBGXthKASE+K8J5ZBnnA+PAvBDiG3OBcmpaDurTURjtjf6qY96uzAAjcfOBIV8DQuDD/R+ujE5St9+k6fXGWXCFAkZEw1wUN5tzs3rKzVLDDqiQqhvxLkgjyHZrhQeXC5Y5A6nylWUdy0QmYJExvSQSJJ1QVqB902Rw275spbFSP1n6GjuLb/igN/psbpViztcaXKqpoO/0Pt1L4Jz1gsIaaH644t2WeD0FVrIj20Lw0bD619V0Fq2jKuXEuAyXYVEoVVlK9pVn8blp2rEuvnbVQAVow1HZYCA18n8TWPC6OM59SQxQdsW1olIQ5eFeVgAsG312vuAfLSAyZMWG98Go9HI8eNVO6tCdPYoDn5QpbMfkwbceP+J1acgfKEj1/0MQSA/z5iF3CYrgQ3QIFcttQ38kOiN+P8BV/6W89JyIJ7UmDHzWNRAr6pbUxijqVf5vxFLSQ2uG2mtMINqhMJYfTJpMri6Ejs1+keN3/NBMjs2Wyi8t656gn0QMDrOZvge853aivOFm0zTvto/BC++tPLoy5OiTv0ge3WnX+MVG+pVR3Memt9u9LsH/IDkXWlMXPVVNV0BrLTKmGPE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
